site_name: gracemaker

theme:
  name: "material"
#  logo: "imgs/logo1.png"  # Path to your logo image
  icon:
    logo: material/library
  features:
    - content.code.copy
#    - navigation.tabs # navigation on the top
    - navigation.sections   # Ensures that nested items are grouped in sections
    - navigation.expand     # Allows for expandable sections in the sidebar
    - navigation.tracking   # Highlights the active section in the sidebar
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "teal"
      accent: "indigo"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "teal"
      accent: "indigo"
      toggle:
        icon: material/brightness-4
        name: Switch to system preference


plugins:
  - search
  - autorefs
  - glightbox

nav:
  - Start: index.md
  - Installation: gracemaker/install.md
  - Quick start: gracemaker/quickstart.md
  - Presets: gracemaker/presets.md
  - Input file: gracemaker/inputfile.md
  - CLI: gracemaker/cli.md
  - Utilities: gracemaker/utilities.md
  - Foundation models: gracemaker/foundation.md
  - Tutorials: gracemaker/tutorials.md
  - FAQs: gracemaker/faq.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      separator: "-"
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#extra_css:
#  - stylesheets/extra.css
