site_name: gracemaker

theme:
  name: "material"

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      separator: "_"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Installation: gracemaker/install.md
    - Quick start: gracemaker/quickstart.md
    - Input file: gracemaker/inputfile.md
    - CLI: gracemaker/cli.md
    - Utilities: gracemaker/utilities.md
    - FAQs: gracemaker/faq.md
