site_name: gracemaker

theme:
  name: "material"
#  logo: "imgs/logo1.png"  # Path to your logo image
  icon:
    logo: material/library
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.sections
    - navigation.top  # Keep the top navigation bar fixed
  palette:
    - scheme: default
      primary: "teal"
      accent: "indigo"
    - scheme: slate
      primary: "indigo"
      accent: "pink"


plugins:
  - search
  - autorefs

nav:
  - Start: index.md
  - Installation: gracemaker/install.md
  - Quick start: gracemaker/quickstart.md
  - Presets: gracemaker/presets.md
  - Input file: gracemaker/inputfile.md
  - CLI: gracemaker/cli.md
  - Utilities: gracemaker/utilities.md
  - FAQs: gracemaker/faq.md
  - Tutorials: gracemaker/tutorials.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "#"
      separator: "-"


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
